/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sat Jul 06 21:47:49 GMT 2024
 */

package org.isf.medicalstock.test;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class MovStockInsertingManager_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.isf.medicalstock.manager.MovStockInsertingManager"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "/home/ec2021-fra/ra247275/Documents/MC646/Projeto Final/Lozavival-projeto-final-mc646-mo409"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(MovStockInsertingManager_ESTest_scaffolding.class.getClassLoader() ,
      "org.isf.utils.db.Auditable",
      "org.isf.medstockmovtype.model.MovementType",
      "org.isf.ward.model.Ward",
      "org.isf.generaldata.MessageBundle",
      "org.isf.utils.exception.OHServiceException",
      "org.isf.medicals.model.Medical",
      "org.isf.utils.exception.model.OHSeverityLevel",
      "org.isf.medtype.model.MedicalType",
      "org.isf.utils.exception.OHDataValidationException",
      "org.isf.supplier.model.Supplier",
      "org.isf.medicalstock.service.MedicalStockIoOperations",
      "org.isf.utils.db.UTF8Control",
      "org.isf.medicalstock.model.Movement",
      "org.isf.medicalstock.model.Lot",
      "org.isf.utils.exception.model.OHExceptionMessage",
      "org.isf.medicalstock.manager.MovStockInsertingManager"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(MovStockInsertingManager_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.isf.medicalstock.manager.MovStockInsertingManager",
      "org.isf.generaldata.MessageBundle",
      "org.isf.generaldata.ConfigurationProperties",
      "org.isf.generaldata.GeneralData",
      "org.isf.utils.exception.model.OHSeverityLevel",
      "org.isf.utils.db.Auditable",
      "org.isf.medicalstock.model.Lot",
      "org.isf.medicalstock.model.Movement",
      "org.isf.medtype.model.MedicalType",
      "org.isf.medicals.model.Medical",
      "org.isf.utils.exception.model.OHExceptionMessage",
      "org.isf.medstockmovtype.model.MovementType",
      "org.isf.ward.model.Ward",
      "org.isf.supplier.model.Supplier",
      "org.isf.utils.exception.OHServiceException",
      "org.isf.utils.exception.OHDataValidationException"
    );
  }
}
