// Generated by GraphWalker (http://www.graphwalker.org)
package org.isf.medicalstock.test;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "org/isf/medicalstock/StockMovement.json")
public interface StockMovement {

    @Vertex()
    void v_BellowCriticalLevel();

    @Edge()
    void e_chargeInvalid();

    @Edge()
    void e_dischargeInvalid();

    @Edge()
    void e_charge();

    @Edge()
    void e_dischargeToEmpty();

    @Vertex()
    void v_OutOfStock();

    @Edge()
    void e_chargeToAbove();

    @Edge()
    void e_discharge();

    @Vertex()
    void v_AboveCriticalLevel();
}
